### 모든 주문 정보 가져오는 요청
GET http://localhost:7020/api/orders

### 특정 주문 상세 정보 가져오는 요청
GET http://localhost:7020/api/orders/1

### 특정 주문 상세 정보 가져오는 요청 (주문이 존재하지 않는 경우)
GET http://localhost:7020/api/orders/1111

### 상품 주문 요청
POST http://localhost:7020/api/orders
Content-Type: application/json

{
  "productId": 1
}

### 상품 주문 요청(상품이 존재하지 않는 경우)
POST http://localhost:7020/api/orders
Content-Type: application/json

{
  "productId": 1000
}

### 상품 주문 요청(잘못된 요청의 경우)
POST http://localhost:7020/api/orders
Content-Type: application/json

{
}

### 주문 수정 요청
PUT http://localhost:7020/api/orders
Content-Type: application/json

{
  "orderId": 1,
  "productId": 2
}

### 주문 수정 요청 (주문이 존재하지 않는 경우)
PUT http://localhost:7020/api/orders
Content-Type: application/json

{
  "orderId": 100,
  "productId": 2
}

### 주문 수정 요청 (상품이 존재하지 않는 경우)
PUT http://localhost:7020/api/orders
Content-Type: application/json

{
  "orderId": 1,
  "productId": 1000
}

### 주문 수정 요청 (잘못된 요청의 경우)
PUT http://localhost:7020/api/orders
Content-Type: application/json

{
  "productId": 1000
}

### 주문 삭제 요청
DELETE http://localhost:7020/api/orders/2

### 주문 삭제 요청(주문이 존재하지 않는 경우)
DELETE http://localhost:7020/api/orders/1111

### Sleep 요청 (Default = 10초)
GET http://localhost:7020/api/sleep

### Sleep 요청 (시간 지정)
GET http://localhost:7020/api/sleep?interval=2

